// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS4C7MPonBM5O79bQCgt2MyjNMOLlSqaY',
    appId: '1:830364758126:web:d73e392e3a0135beddb67f',
    messagingSenderId: '830364758126',
    projectId: 'dino-dine',
    authDomain: 'dino-dine.firebaseapp.com',
    storageBucket: 'dino-dine.firebasestorage.app',
    measurementId: 'G-YG7VBH814R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUQcQjC_ZbKBOg0ZCENGk-5pWbqg-mpqs',
    appId: '1:830364758126:android:9c4cbfff7bc3e671ddb67f',
    messagingSenderId: '830364758126',
    projectId: 'dino-dine',
    storageBucket: 'dino-dine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoqDva1B-vD65od0gZ807uVRUez6pkVxo',
    appId: '1:830364758126:ios:46e4cd27f43e646addb67f',
    messagingSenderId: '830364758126',
    projectId: 'dino-dine',
    storageBucket: 'dino-dine.firebasestorage.app',
    iosBundleId: 'com.example.billingapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoqDva1B-vD65od0gZ807uVRUez6pkVxo',
    appId: '1:830364758126:ios:46e4cd27f43e646addb67f',
    messagingSenderId: '830364758126',
    projectId: 'dino-dine',
    storageBucket: 'dino-dine.firebasestorage.app',
    iosBundleId: 'com.example.billingapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS4C7MPonBM5O79bQCgt2MyjNMOLlSqaY',
    appId: '1:830364758126:web:9c5e0b22697aedc9ddb67f',
    messagingSenderId: '830364758126',
    projectId: 'dino-dine',
    authDomain: 'dino-dine.firebaseapp.com',
    storageBucket: 'dino-dine.firebasestorage.app',
    measurementId: 'G-CXGHJBKGN6',
  );
}
